name: ud_cyber_crypto
description: A library for common encryption algorithms.
# version: 0.1.1
# homepage: https://www.example.com
# author: Michael Jurkoic <mjjurkoic@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
